POST http://portal1.maxitv.com.br/administration/

Authorization: bearer 78409cda55ca6cc4a22b5731be6e3b9bfe06f1c4
###### LOGIN VIA HTTP HEADER
POST http://partner.maxitv.com.br/maxitv.php?login=admin&senha=master10&action=PartnerLogin HTTP/1.1
Content-Type: application/json
##### LISTA PROVEDOR ATIVO
GET  http://partner.maxitv.com.br/maxitv.php?action=ListarProviders&somenteAtivos=1 HTTP/1.1
Content-Type: application/xml
Authorization:ey0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjAiLCJwcm92aWRlcl9pZCI6IjAiLCJhZG1pbnVzZXJfaWQiOiIwIiwiZGVzY3AiOiJBZG1pbiBNYXN0ZXIiLCJsb2dpbiI6ImFkbWlIiwic2VuaGEiOiJtYXN0ZXIxMCIsImFwaV9sb2dpbiI6ImdsZXlkc29uQHZpYWNhc3QuY29tLmJyIiwiYXBpX3NlbmhhIjoiZ2JjMjAxMmNlY2kiLCJtYXN0ZXIiOiIxIiwib3JnSWQiOiIiLCJzdHJlZXQiOiIiLCJ0b3duIjoiIiwiemlwIjoiIiwiYXRpdm8iOiIxIiwid2Vic2l0ZSI6IiIsImV4cGlyZXNJbiI6IjEgZGF5In0.sYRPBzF-Z8w8enXdyj_KyCmPIQZDJ--LV-M5e8Qgg5A
#### LISTA PROVEDOR
GET  http://partner.maxitv.com.br/maxitv.php?provider_id=43&texto=&action=listarCustomer&offset=0&limit=30 HTTP/1.1
Content-Type: application/xml
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjAiLCJwcm92aWRlcl9pZCI6IjAiLCJhZG1pbnVzZXJfaWQiOiIwIiwiZGVzY3AiOiJBZG1pbiBNYXN0ZXIiLCJsb2dpbiI6ImFkbWluIiwic2VuaGEiOiJtYXN0ZXIxMCIsImFwaV9sb2dpbiI6ImdsZXlkc29uQHZpYWNhc3QuY29tLmJyIiwiYXBpX3NlbmhhIjoiZ2JjMjAxMmNlY2kiLCJtYXN0ZXIiOiIxIiwib3JnSWQiOiIiLCJzdHJlZXQiOiIiLCJ0b3duIjoiIiwiemlwIjoiIiwiYXRpdm8iOiIxIiwid2Vic2l0ZSI6IiIsImV4cGlyZXNJbiI6IjEgZGF5In0.sYRPBzF-Z8w8enXdyj_KyCmPIQZDJ--LV-M5e8Qgg5A
###
GET  http://partner.maxitv.com.br/maxitv.php?action=ListarPlanosDoCliente=1 HTTP/1.1
Content-Type: application/xml
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjAiLCJwcm92aWRlcl9pZCI6IjAiLCJhZG1pbnVzZXJfaWQiOiIwIiwiZGVzY3AiOiJBZG1pbiBNYXN0ZXIiLCJsb2dpbiI6ImFkbWluIiwic2VuaGEiOiJtYXN0ZXIxMCIsImFwaV9sb2dpbiI6ImdsZXlkc29uQHZpYWNhc3QuY29tLmJyIiwiYXBpX3NlbmhhIjoiZ2JjMjAxMmNlY2kiLCJtYXN0ZXIiOiIxIiwib3JnSWQiOiIiLCJzdHJlZXQiOiIiLCJ0b3duIjoiIiwiemlwIjoiIiwiYXRpdm8iOiIxIiwid2Vic2l0ZSI6IiIsImV4cGlyZXNJbiI6IjEgZGF5In0.sYRPBzF-Z8w8enXdyj_KyCmPIQZDJ--LV-M5e8Qgg5A
####
GET http://partner.maxitv.com.br/maxitv.php?action=listarPlanosGravacao&id=727 HTTP/1.1
Content-Type: application/xml
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjAiLCJwcm92aWRlcl9pZCI6IjAiLCJhZG1pbnVzZXJfaWQiOiIwIiwiZGVzY3AiOiJBZG1pbiBNYXN0ZXIiLCJsb2dpbiI6ImFkbWluIiwic2VuaGEiOiJtYXN0ZXIxMCIsImFwaV9sb2dpbiI6ImdsZXlkc29uQHZpYWNhc3QuY29tLmJyIiwiYXBpX3NlbmhhIjoiZ2JjMjAxMmNlY2kiLCJtYXN0ZXIiOiIxIiwib3JnSWQiOiIiLCJzdHJlZXQiOiIiLCJ0b3duIjoiIiwiemlwIjoiIiwiYXRpdm8iOiIxIiwid2Vic2l0ZSI6IiIsImV4cGlyZXNJbiI6IjEgZGF5In0.sYRPBzF-Z8w8enXdyj_KyCmPIQZDJ--LV-M5e8Qgg5A
###
GET http://partner.maxitv.com.br/maxitv.php?provider_id=27&texto=&action=listarCustomer&offset=0&limit=200 HTTP/1.1
Content-Type: application/xml
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjAiLCJwcm92aWRlcl9pZCI6IjAiLCJhZG1pbnVzZXJfaWQiOiIwIiwiZGVzY3AiOiJBZG1pbiBNYXN0ZXIiLCJsb2dpbiI6ImFkbWluIiwic2VuaGEiOiJtYXN0ZXIxMCIsImFwaV9sb2dpbiI6ImdsZXlkc29uQHZpYWNhc3QuY29tLmJyIiwiYXBpX3NlbmhhIjoiZ2JjMjAxMmNlY2kiLCJtYXN0ZXIiOiIxIiwib3JnSWQiOiIiLCJzdHJlZXQiOiIiLCJ0b3duIjoiIiwiemlwIjoiIiwiYXRpdm8iOiIxIiwid2Vic2l0ZSI6IiIsImV4cGlyZXNJbiI6IjEgZGF5In0.sYRPBzF-Z8w8enXdyj_KyCmPIQZDJ--LV-M5e8Qgg5A
###
GET http://partner.maxitv.com.br/maxitv.php?action=ListarDispositivos&id=1 HTTP/1.1
Content-Type: application/xml
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjAiLCJwcm92aWRlcl9pZCI6IjAiLCJhZG1pbnVzZXJfaWQiOiIwIiwiZGVzY3AiOiJBZG1pbiBNYXN0ZXIiLCJsb2dpbiI6ImFkbWluIiwic2VuaGEiOiJtYXN0ZXIxMCIsImFwaV9sb2dpbiI6ImdsZXlkc29uQHZpYWNhc3QuY29tLmJyIiwiYXBpX3NlbmhhIjoiZ2JjMjAxMmNlY2kiLCJtYXN0ZXIiOiIxIiwib3JnSWQiOiIiLCJzdHJlZXQiOiIiLCJ0b3duIjoiIiwiemlwIjoiIiwiYXRpdm8iOiIxIiwid2Vic2l0ZSI6IiIsImV4cGlyZXNJbiI6IjEgZGF5In0.sYRPBzF-Z8w8enXdyj_KyCmPIQZDJ--LV-M5e8Qgg5A